### ISSUE TITLE
Disconnect issue

### ISSUE THREAD

**Issue by mahendra-virtueinfo** [twilio/video-quickstart-js#14] opened 2017-05-30 12:46 UTC
Hello Team,

**Here i faced two issues:**
**Issue 1:**
   -> When i joined room first time then everything works fine.
   -> When i refresh (soft refresh) browser tab, then video disconnect.
  -> When i join again then video rendered without stream(black screen)
  -> When i try again 2-3 time randomly then automatically working. it is happening every test.
**Issue 2:**
  -> When i disconnect room or track.stop it can not stop video access from my camera, light is on.

OS : Ubuntu 14.4 LTS
Browser : Chrome - Version 58.0.3029.110 (64-bit)

**Any idea how to stop camera access when call stop ?**

**Comment by lmatheus** [comment] 2018-08-21 13:42
Same behaviour on my part, duplicate of #51

**Closed** 2020-01-23 21:59 UTC
