### ISSUE TITLE
Unable to share screen

### ISSUE THREAD

**Issue by likhit-vivek** [twilio/video-quickstart-js#133] opened 2020-06-01 06:04 UTC
This is the console error:
`Uncaught (in promise) TypeError: window.navigator.mediaDevices.getDisplaymedia is not a function
    at window.shareScreen (bundle.js:234)
    at HTMLButtonElement.onclick ((index):43)`

This is my code:
`stream = await navigator.mediaDevices.getDisplaymedia({video: true});
    screenTrack = new LocalVideoTrack(stream.getTracks()[0]);
    window.room.localParticipant.publishTrack(screenTrack);`

I'm using Google Chrome (Version 81.0.4044.138 (Official Build) (64-bit)) on Ubuntu 18.04.
Pls help!

**Comment by PikaJoyce** [comment] 2020-06-03 18:35
Hi @likhit-vivek 

Thank you for reporting this issue. I will investigate this as this seems to be unexpected behavior and get back to you as soon as I can.

Best,
Joyce

**Comment by PikaJoyce** [comment] 2020-06-16 02:07
Hey there @likhit-vivek!

I was able to test this out and it seems that the quickstart app is having the same issues although the screen share example works fine on Ubuntu/Chrome. I can log `window.navigator.mediaDevices` in the console. 

Will it be possible for you to provide me with more details such as more code? 

Also, I realized that you are using `window.navigator.mediaDevices.getDisplaymedia` which is deprecated according to the documentation. Have you considered switching over to  `Navigator.getUserMedia()`?

In the meantime, I will try to investigate further as it seems like the quickstart is exhibiting this issue as well. Let me know if this helps or if you have any other questions! 

Thank you for your patience,
Joyce

**Comment by PikaJoyce** [comment] 2020-06-24 01:21
Hey @likhit-vivek! 

I took a look at your code and upon closer inspection, I noticed that you were calling `getDisplaymedia` instead of `getDisplayMedia` which would resolve your issue. 

I will be closing this issue now and if you have any further problems, feel free to open another issue. 

Thanks,
Joyce

**Closed by PikaJoyce** 2020-06-24 01:21 UTC
